### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by ThomasADavis** [minitriga/axians-netbox-plugin-pdu#11]
```Traceback (most recent call last):
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/db/models/query.py", line 575, in update_or_create
    obj = self.select_for_update().get(**kwargs)
  File "/opt/netbox/venv/lib64/python3.6/site-packages/cacheops/query.py", line 390, in get
    return qs._no_monkey.get(qs, *args, **kwargs)
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/db/models/query.py", line 417, in get
    self.model._meta.object_name
axians_netbox_pdu.models.PDUStatus.DoesNotExist: PDUStatus matching query does not exist.



During handling of the above exception, another exception occurred:



Traceback (most recent call last):
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/db/models/fields/__init__.py", line 1772, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'NOSUCHINSTANCE'



The above exception was the direct cause of the following exception:



Traceback (most recent call last):
  File "/opt/netbox/venv/lib64/python3.6/site-packages/rq/worker.py", line 883, in perform_job
    rv = job.perform()
  File "/opt/netbox/venv/lib64/python3.6/site-packages/rq/job.py", line 657, in perform
    self._result = self._execute()
  File "/opt/netbox/venv/lib64/python3.6/site-packages/rq/job.py", line 663, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/opt/netbox/venv/lib64/python3.6/site-packages/axians_netbox_pdu/worker.py", line 36, in collect_power_usage_info
    pdu_status = PDUStatus.objects.update_or_create(device=device, defaults={"power_usage": power_usage.value})
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/db/models/query.py", line 580, in update_or_create
    obj, created = self._create_object_from_params(kwargs, params, lock=True)
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/db/models/query.py", line 596, in _create_object_from_params
    obj = self.create(**params)
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/db/models/query.py", line 433, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 746, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 784, in save_base
    force_update, using, update_fields,
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 926, in _do_insert
    using=using, raw=raw,
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1391, in execute_sql
    for sql, params in self.as_sql():
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1336, in as_sql
    for obj in self.query.objs
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1336, in <listcomp>
    for obj in self.query.objs
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1335, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1276, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/db/models/fields/__init__.py", line 821, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/db/models/fields/__init__.py", line 816, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/db/models/fields/__init__.py", line 1776, in get_prep_value
    ) from e
ValueError: Field 'power_usage' expected a number but got 'NOSUCHINSTANCE'.```
```

**Comment by minitriga** [comment]
Hello @ThomasADavis, Could you please provide some more information regarding how you are able to reproduce this issue?

**Comment by minitriga** [comment]
@ThomasADavis it looks like your SNMP string is returning NOSUCHINSTANCE. 

Could you provide the following information:

- PDU Model
- PDU SNMP OID String
- Output of the SNMP GET on that string (perform manually)

**Comment by minitriga** [comment]
Closed as there is no activity.
