### ISSUE TITLE
Netbox 2.10.0+ Compatibility

### ISSUE THREAD

**Issue by ndom91** [minitriga/axians-netbox-plugin-pdu#17]
So apparently they changed a good bit about how custom fields are handled in the models, among other things.

See release notes: https://github.com/netbox-community/netbox/releases/tag/v2.10.0

**Comment by ndom91** [comment]
Although that import statement update allows netbox to load with your plugin enabled, there are still a few smaller issues. 

1) They seem to have updated a lot of the icons in 2.10.0+ as well, so that needs updating:

![image](https://user-images.githubusercontent.com/7415984/103536779-6c5b1680-4e93-11eb-8e12-53ae724fadb5.png)

2) The worker / background task also seems to need some namespace updates. Here's a log from a most recent failed job:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rq/worker.py", line 934, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.8/dist-packages/rq/job.py", line 686, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.8/dist-packages/rq/job.py", line 692, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rq/job.py", line 211, in func
    return import_attribute(self.func_name)
  File "/usr/local/lib/python3.8/dist-packages/rq/utils.py", line 128, in import_attribute
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/axians_netbox_pdu/__init__.py", line 3, in <module>
    from extras.plugins import PluginConfig
ModuleNotFoundError: No module named 'extras'
```

**Comment by ndom91** [comment]
Seems to work though even though it throws errors about "no module named extras" found.

![image](https://user-images.githubusercontent.com/7415984/103542547-666a3300-4e9d-11eb-91e0-9b48375d48c6.png)

![image](https://user-images.githubusercontent.com/7415984/103542579-6ff39b00-4e9d-11eb-9235-e34e4a955adc.png)
